### ISSUE TITLE
Script to get the spectrograms

### ISSUE THREAD

**Issue by mathigatti** [minzwon/tag-based-music-retrieval#1]
Hi, thanks for sharing this awesome project!

By any change do you have the script you used to generate the spectrograms (the npy files)?

Thanks in advance :)

**Comment by mathigatti** [comment]
In the article it says _"For input preprocessing, audio files are downsampled to 22.5kHz then converted to Mel spectrograms using 1024-point FFT with 50% overlap and 128 Mel bands"_. And in the [main.py](https://github.com/Un-bias/tag-based-music-retrieval/blob/master/train/main.py#L42) it looks like input_length is 173. Based on that I ended up with this, not sure if I'm missing something.

```python
import librosa
import numpy as np

def audio2spec(audio_path, n_mels=128, n_frames = 173, n_fft = 1024, hop_length = 512, sr = 22050):
    y, sample_rate = librosa.load(audio_path, mono=True, sr=sr)
    S = librosa.feature.melspectrogram(y = y, sr = sample_rate, n_mels=n_mels, n_fft = n_fft, hop_length=hop_length, fmax = 8000)
    
    # convert to Decibel
    S = librosa.power_to_db(S, ref = np.max)

    center_frame_idx = S.shape[1] / 2
    offset = int(center_frame_idx - n_frames / 2)
    
    return S[:,offset:(offset+n_frames)]

song_path = "your_audio.mp3"
spec = audio2spec(song_path)
with open("your_spec.npy","wb") as f:
    np.save(f, spec)
```

**Comment by minzwon** [comment]
Hi Mathias,

since I used Librosa, your code is almost identical to my preprocessing. But forget about the lines after you convert it to Decibel. Just store it as it is. 

The role of input_length is in `data_loader.py`.
For training, I crop a random chunk (173 frames = about 4sec) then feed it to the network. For evaluation, I take 8 chunks (`num_chunk`=8) from equally distributed offset positions of the audio then I average the predictions. Check `def song_to_emb` in `solver.py`.

**Comment by mathigatti** [comment]
Awesome I simplified it then, removing the Decibel part and saving the full spectrogram, not slicing it. Thank you very much!

```python
def audio2spec(audio_path, n_mels=128, n_fft = 1024, hop_length = 512, sr = 22050):
    y, sample_rate = librosa.load(audio_path, mono=True, sr=sr)
    S = librosa.feature.melspectrogram(y = y, sr = sample_rate, n_mels=n_mels, n_fft = n_fft, hop_length=hop_length, fmax = 8000)
    return S
```

**Comment by minzwon** [comment]
Sorry for making confusion. You want to keep the line `S = librosa.power_to_db(S, ref = np.max)`. I meant to remove other lines after that since chunking will be handled in the data loader!

**Comment by mathigatti** [comment]
Right! Sorry, I misread you answer. I'm running it with power_to_db now, thanks!
